"""
Voice front-end for the bank RAG agent, running against a SELF-HOSTED
LiveKit server (see docker-compose.yml) — not LiveKit Cloud.

Uses Gemini end-to-end (no OpenAI):
  - Speech in/out: Gemini Live API (google.beta.realtime.RealtimeModel),
    authenticated with GEMINI_API_KEY / GOOGLE_API_KEY only — no separate
    Google Cloud service account needed.
  - Answers: NOT generated by the realtime model's own knowledge. It is
    instructed to call the `lookup_bank_info` tool for every question,
    which runs rag.get_answer() (the same scoped RAG pipeline as the
    text CLI) and returns the grounded answer for it to speak back.

Why not a plain Gemini STT/TTS pair? Gemini has no standalone STT model
reachable with just an API key — LiveKit's Google plugin only exposes
discrete Speech-to-Text/Text-to-Speech via Google Cloud (Chirp), which
needs a GOOGLE_APPLICATION_CREDENTIALS service account file, not your
Gemini API key. The Live API sidesteps that entirely.

Trade-off to know about: a realtime speech-to-speech model is more
likely to lightly rephrase the tool's answer than a strict
STT -> text-answer -> TTS pipeline would. The system instructions below
tell it to stay close to the tool's wording, but this is looser grounding
than the text CLI (`rag.py ask`) gives you. If you need stricter
word-for-word grounding, the alternative is Google Cloud STT/TTS
(discrete, non-realtime) with a GCP service account — ask if you want
that version instead.

Setup:
  pip install "livekit-agents[silero,google]" python-dotenv
  docker compose up -d          # starts the self-hosted LiveKit server
  cp .env.example .env          # fill in GEMINI_API_KEY (used as GOOGLE_API_KEY too)
  python voice_agent.py console # talk to it right in your terminal, or:
  python voice_agent.py dev     # run as a worker that joins real rooms

NOTE ON API STABILITY: livekit-agents and the Gemini Live API both move
fast. If imports/model names fail, check:
  https://docs.livekit.io/agents/integrations/realtime/gemini
for the current equivalent — rag.py itself has no dependency on any of
this and keeps working standalone via `python rag.py ask`.
"""

import logging
import os
import asyncio
from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentServer,
    AgentSession,
    JobContext,
    cli,
    function_tool,
)
from livekit.plugins import google
import rag

load_dotenv()

# The google plugin reads GOOGLE_API_KEY; reuse GEMINI_API_KEY if that's
# the only one set, so you don't need to duplicate the same key twice.
if "GOOGLE_API_KEY" not in os.environ and "GEMINI_API_KEY" in os.environ:
    os.environ["GOOGLE_API_KEY"] = os.environ["GEMINI_API_KEY"]

logger = logging.getLogger("bank-voice-agent")
logger.setLevel(logging.INFO)

server = AgentServer()

SYSTEM_INSTRUCTIONS = """You are a voice assistant for Armenian bank loans,
deposits, and branch information.

You must NEVER answer a question from your own knowledge. For every
question the caller asks, call the lookup_bank_info tool with their
question, exactly as asked. Then speak the tool's returned text back to
the caller, staying as close to its wording as you can — you may smooth
it into natural spoken phrasing, but do not add facts, numbers,
addresses, or claims that are not present in what the tool returned.

If the tool's answer says the information could not be found, or that
the question is out of scope, say that plainly — do not try to be more
helpful than the tool's answer allows."""


def to_spoken_text(result: dict) -> str:
    """Turn a rag.get_answer() result into something pleasant to hear.
    Reading full URLs aloud is bad UX, so we mention institution names
    instead of the raw links; the text CLI (rag.py) still shows full URLs."""
    answer = result["answer"]
    if result["status"] == "ok" and result["sources"]:
        institutions = sorted({s[0] for s in result["sources"]})
        answer += " This is based on official information from " + ", ".join(institutions) + "."
    return answer


class BankVoiceAgent(Agent):
    def __init__(self) -> None:
        super().__init__(instructions=SYSTEM_INSTRUCTIONS)

    async def on_enter(self):
       await self.session.generate_reply(
            instructions=(
                "Greet the caller briefly and say you can answer questions "
                "about loans, deposits, and branch locations at supported "
                "banks. Do not call any tool for this greeting."
            )
        )

    @function_tool
    async def lookup_bank_info(self, question: str) -> str:
        """Look up an answer to a question about bank loans, deposits, or
        branch locations, using only official scraped data. Call this for
        every user question before responding — never answer from your
        own knowledge.

        Args:
            question: The user's question, as they asked it.
        """
        result = await asyncio.to_thread(rag.get_answer, question)
        return to_spoken_text(result)


@server.rtc_session()
async def entrypoint(ctx: JobContext):
    ctx.log_context_fields = {"room": ctx.room.name}

    session = AgentSession(
        llm=google.beta.realtime.RealtimeModel(
            voice="Puck",
            temperature=0.2,  # low temperature: stick close to tool output
        ),
        # No separate stt/tts: the Gemini Live API handles speech in and
        # out directly as part of the realtime model above.
    )

    await session.start(agent=BankVoiceAgent(), room=ctx.room)
    await ctx.connect()


if __name__ == "__main__":
    cli.run_app(server)
